export { default as Movies } from "./Movies";
export { default as AllMovies } from "./AllMovies";
export { default as MovieDetails } from "./MovieDetails";
export { default as Account } from "./Account";
export { default as AuthLogin } from "./Auth/Login";
export { default as AuthRegister } from "./Auth/Register";
export { default as Genres } from "./Genres";
export { default as MoviesByGenre } from "./MoviesByGenre";
export { default as Search } from "./Search";
